version: '3.1'
services:
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    expose:
      - "3306"
    ports:
      - "3306:3306"    
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: node
      MYSQL_ALLOW_EMPTY_PASSWORD: ok
    volumes:
      - ~/data:/var/lib/mysql

# docker-compose up -d      
# docker exec -it typescript-express-mysql-api-fernando-herrera_mysql_1 bash