version: '3.1'
# Use root/example as user/password credentials
networks:
  app-tier:
    driver: bridge

services:
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    expose:
      - "3306"
    ports:
      - "3306:3306"    
    networks:
      - app-tier          
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: node
      MYSQL_ALLOW_EMPTY_PASSWORD: ok
    volumes:
      - ~/data:/var/lib/mysql
# ~/data = C:\Users\oscar.montoya\data

# docker-compose up -d      
# docker exec -it typescript-express-mysql-api-fernando-herrera_mysql_1 bash